# Site settings
title: Liam's Development Blog
email: mail@liam-conroy.com
description: > # this means to ignore newlines until "baseurl:"
  Programming blog of Liam Conroy, freelance software engineer 
  living and working in Kyoto. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liaminjapan.github.io" # the base hostname & protocol for your site
twitter_username: LiamInJapan
github_username:  LiamInJapan

# Build settings
markdown: kramdown
